{% set version = "1.0.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-waterfalls
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/waterfalls_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/waterfalls/waterfalls_{{ version }}.tar.gz
  sha256: 0dc8b94edc37239c0991cc5f435322f1ccf85df9f0b321f9f003ba0023e541f2

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-ggplot2 >=2.0.0
  run:
    - r-base
    - r-ggplot2 >=2.0.0

test:
  commands:
    - $R -e "library('waterfalls')"           # [not win]
    - "\"%R%\" -e \"library('waterfalls')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=waterfalls
  license: MIT
  summary: A not uncommon task for quants is to create 'waterfall charts'. There seems to be no simple way to do this in 'ggplot2' currently. This package contains a single function (waterfall) that simply draws a waterfall chart in a 'ggplot2' object. Some flexibility is provided, though often the object created will need
    to be modified through a theme.
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: waterfalls
# Type: Package
# Title: Create Waterfall Charts using 'ggplot2' Simply
# Date: 2018-01-15
# Version: 0.1.2
# Author: Hugh Parsonage
# Maintainer: Hugh Parsonage <hugh.parsonage+waterfall@gmail.com>
# Description: A not uncommon task for quants is to create 'waterfall charts'. There seems to be no simple way to do this in 'ggplot2' currently. This package contains a single function (waterfall) that simply draws a waterfall chart in a 'ggplot2' object. Some flexibility is provided, though often the object created will need to be modified through a theme.
# License: MIT + file LICENSE
# Imports: ggplot2 (>= 2.0.0), grDevices
# LazyData: TRUE
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-01-26 00:14:09 UTC; hughp
# Repository: CRAN
# Date/Publication: 2018-01-26 04:04:30 UTC
