appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: OEqfFONotJtKUnS5dakGuzdGGzRbxdSk9gyxl8ICypoJ7e+AqE+DBTpw9qnuongFKDme/P3dO35SjRaf56tMMI4F4COneaAwFjf48dFlqhW3MDI35SVDYwwbM9twNascyMkX6+vPy+bPkhTyg665sHULrJeb1s1yTn3YIFzOZKSdm8Kuqh3ikDEbs9wA9/2aUUIIO03LLmoogb5Cbg12qOJMoC19NsOptHOF26/r+dabmIWxR11aio1grextgrL3Djw7kCv63Mg0QRn6Qp2tos7M9u3HvrQDOX8CV2BTcf3bqo7q5zt2zw9YcMJT75eWdPOJPlUuwCviT7tPDs3LSR+ATZtB2HVEf3ciO3eg7vzYF/4gUMd1nY4cshCkPlZzcTh9av/s6pA5gXnltuG15CVuOiRopB29YS7pNYdBgZL1HKQmnAbPis++4wmdeqhVqjSdWj+KMgkADjJwsTTy9aYmHNIOaUrneB+ENWu1AoAerjwWifYLzp7TgkG+EMVi2Q7pYsWhxw/nZjV6JwMmoHIN2nXj0nP5alCmSfs8x5oSDNFIp/KzRyBnBBhDEKziKdcGP2plruKGMsCPkkdyYG8fngK1Fx6rYqneX4id5uFHya+IjKp/hLs9+ZB5gVDiqP7rnDS0quV2uTALVnnE/iyCr9lx/Dc96tzDDL5XyA4=
